const swaggerAutogen = require('swagger-autogen')({ openapi: '3.1.0' });
const path = require('path');

const PORT = process.env.PORT || 3000;

const swaggerGen = () => {
  const doc = {
    info: {
      version: '3.1.0',
      author: '@thnhan2',
      title: 'Food Service API',
      description: 'Documentation automatically generated by the <b>swagger-autogen</b> module.',
    },
    host: `localhost:${PORT}`,
    basePath: '/',
    schemes: ['http', 'https'],
    consumes: ['application/json'],
    produces: ['application/json'],
    tags: [
      {
        name: 'Categories',
        description: 'Endpoints',
      },
    ],
  };

  const outputFile = './output/swagger-output.json';
  const endpointsFiles = [path.join(__dirname, '../app.js')];

  swaggerAutogen(outputFile, endpointsFiles, doc).then(async () => {
    await require(path.join(__dirname, '../app.js'));
  });
};

module.exports = swaggerGen;
